### PR TITLE
Function to Draw Ellipse Added

### PR DESCRIPTION
**Pull request by Prajwal7842**
Drawing ellipse function along with its documentation has been updated.

### CODE REVIEW

**Comment by woolllff** [comment]
what about the start angle

**Comment by woolllff** [comment]
ooh sorry you just commited i didnt see

**Comment by woolllff** [comment]
listen make the index file in a different branch and send the pr for that branch as well.
leave the changes that you want in the canvas here

**Comment by Prajwal7842** [comment]
Okay, Thanks for the advice @woolllff . Will send it soon.

**Comment by rtwksai** [comment]
@woolllff can you merge this PR? We could start working with this feature once this gets added

**Comment by woolllff** [comment]
@Prajwal7842 you have to remove the index file from here and put it in a different branch , let the index here be the original index.

**Pull request closed without merging**
